### ISSUE TITLE
Loading of the main page takes over 30 seconds in Moodle 3.2

### ISSUE THREAD

**Issue by reactor0138** [frankkoch/moodle-mod_studentquiz#15] opened 2017-04-30 22:30 UTC
Once you click on the student quiz (in moodle 3.2) it take over 30 seconds to load the page even with only 1 or 2 questions in the bank. This puts students off from question creation and being able to quickly do quizzes using the filters

**Comment by frankkoch** [comment] 2017-05-11 12:51
The initial opening of a StudentQuiz-activity might take a little long. I'm currently running a class with 160 questions and hundreds of quiz-executions. The initial opening takes about 10 seconds. A re-opening performs much faster.

We want to improve performance in further releases.

**Comment by eXpl0it3r** [comment] 2017-05-11 13:01
Please keep in mind that performance can also highly depend on your underlying system. If you're running this on a production system, please ensure that you've configured your web and MySQL/PostgreSQL server for best performance. If the possibility exists, you may also want to ask your server operators to increase memory or processing speed.

StudentQuiz is database heavy, so that might be the first step to try an optimize. We'll be running more performance tests and hope to find and fix some potential bottlenecks.

**Comment by nwp90** [comment] 2017-05-11 22:03
Seems the problem is that the query being run is causing multiple sequential scans over the entire question attempts table. And the whole query is being run twice (load_questions being run twice).

```
                                                                               QUERY PLAN                                         
                                      
----------------------------------------------------------------------------------------------------------------------------------
--------------------------------------
 Sort  (cost=2914592.18..2914593.39 rows=487 width=386)
   Sort Key: q.qtype, q.name
   ->  Merge Right Join  (cost=2741238.19..2914570.44 rows=487 width=386)
         Merge Cond: (qa.questionid = q.id)
         ->  Group  (cost=2183342.13..2289883.41 rows=5327064 width=24)
               Group Key: qa.questionid, (count(*)), (count(*))
               ->  Sort  (cost=2183342.13..2196659.79 rows=5327064 width=24)
                     Sort Key: qa.questionid, (count(*)), (count(*))
                     ->  Hash Left Join  (cost=1107346.08..1369680.32 rows=5327064 width=24)
                           Hash Cond: (qa.questionid = mdl_question_attempts_1.questionid)
                           ->  Merge Right Join  (cost=557767.97..799858.49 rows=5327064 width=16)
                                 Merge Cond: (mdl_question_attempts.questionid = qa.questionid)
                                 ->  Sort  (cost=557767.54..557798.68 rows=12456 width=16)
                                       Sort Key: mdl_question_attempts.questionid
                                       ->  HashAggregate  (cost=556671.13..556795.69 rows=12456 width=8)
                                             Group Key: mdl_question_attempts.questionid
                                             ->  Seq Scan on mdl_question_attempts  (cost=0.00..536124.64 rows=4109297 width=8)
                                                   Filter: (responsesummary IS NOT NULL)
                                 ->  Index Only Scan using mdl_quesatte_que_ix on mdl_question_attempts qa  (cost=0.43..187617.37 
rows=5327064 width=8)
                           ->  Hash  (cost=549577.10..549577.10 rows=81 width=16)
                                 ->  HashAggregate  (cost=549575.48..549576.29 rows=81 width=8)
                                       Group Key: mdl_question_attempts_1.questionid
                                       ->  Seq Scan on mdl_question_attempts mdl_question_attempts_1  (cost=0.00..549442.30 rows=2
6635 width=8)
                                             Filter: (rightanswer = responsesummary)
         ->  Materialize  (cost=557896.06..558091.47 rows=17 width=354)
               ->  Nested Loop Left Join  (cost=557896.06..558091.42 rows=17 width=354)
                     ->  Merge Left Join  (cost=557895.78..557958.15 rows=17 width=335)
                           Merge Cond: (q.id = mqa.questionid)
                           ->  Sort  (cost=128.24..128.28 rows=17 width=327)
                                 Sort Key: q.id
                                 ->  Nested Loop  (cost=86.32..127.90 rows=17 width=327)
                                       ->  Index Scan using mdl_quescate_id_pk on mdl_question_categories qc  (cost=0.29..8.30 rows=1 width=16)
                                             Index Cond: (id = 21987)
                                       ->  Hash Right Join  (cost=86.04..119.42 rows=17 width=319)
                                             Hash Cond: (mdl_studentquiz_question.questionid = q.id)
                                             ->  Seq Scan on mdl_studentquiz_question  (cost=0.00..27.00 rows=1700 width=10)
                                             ->  Hash  (cost=85.82..85.82 rows=17 width=317)
                                                   ->  Hash Right Join  (cost=79.06..85.82 rows=17 width=317)
                                                         Hash Cond: (mdl_studentquiz_vote.questionid = q.id)
                                                         ->  HashAggregate  (cost=32.93..36.93 rows=200 width=16)
                                                               Group Key: mdl_studentquiz_vote.questionid
                                                               ->  Seq Scan on mdl_studentquiz_vote  (cost=0.00..23.10 rows=1310 width=16)
                                                         ->  Hash  (cost=45.93..45.93 rows=17 width=285)
                                                               ->  Hash Right Join  (cost=41.17..45.93 rows=17 width=285)
                                                                     Hash Cond: (mdl_studentquiz_comment.questionid = q.id)
                                                                     ->  HashAggregate  (cost=22.90..24.90 rows=200 width=40)
                                                                           Group Key: mdl_studentquiz_comment.questionid
                                                                           ->  Seq Scan on mdl_studentquiz_comment  (cost=0.00..18.60 rows=860 width=40)
                                                                     ->  Hash  (cost=18.05..18.05 rows=17 width=277)
                                                                           ->  Index Scan using mdl_ques_cat_ix on mdl_question q  (cost=0.42..18.05 rows=17 width=277)
                                                                                 Index Cond: (category = 21987)
                                                                                 Filter: (parent = 0)
                           ->  Sort  (cost=557767.54..557798.68 rows=12456 width=16)
                                 Sort Key: mqa.questionid
                                 ->  HashAggregate  (cost=556671.13..556795.69 rows=12456 width=8)
                                       Group Key: mqa.questionid
                                       ->  Seq Scan on mdl_question_attempts mqa  (cost=0.00..536124.64 rows=4109297 width=8)
                                             Filter: (responsesummary IS NOT NULL)
                     ->  Index Scan using mdl_user_id_pk on mdl_user uc  (cost=0.28..7.83 rows=1 width=27)
                           Index Cond: (id = q.createdby)
(60 rows)
```

**Comment by nwp90** [comment] 2017-05-11 22:40
Seems that explicitly joining mdl_question_attempts to mdl_questions with `ON qa.questionid = q.id AND q.category = :catid` in each case will reduce query time from 25 seconds to 11 milliseconds.

**Comment by nwp90** [comment] 2017-05-11 23:29
Oh, you should re-open this issue - the query is horrendously inefficient, there's no doubt about that.

**Comment by nwp90** [comment] 2017-05-14 21:07
To demonstrate what I mean:

bad:
```
explain SELECT q.hidden, q.category, q.id, q.qtype, q.name,
 q.questiontext, q.questiontextformat, qc.contextid, q.createdby,
 uc.firstnamephonetic AS creatorfirstnamephonetic,
 uc.lastnamephonetic AS creatorlastnamephonetic,
 uc.middlename AS creatormiddlename,
 uc.alternatename AS creatoralternatename,
 uc.firstname AS creatorfirstname,
 uc.lastname AS creatorlastname,
 q.timecreated, ap.approved, vo.vote, dl.difficultylevel, pr.practice, co.comment
FROM mdl_question q 
 JOIN mdl_question_categories qc ON qc.id = q.category
 LEFT JOIN mdl_user uc ON uc.id = q.createdby
 LEFT JOIN
  (SELECT questionid, approved FROM mdl_studentquiz_question) ap ON ap.questionid = q.id
 LEFT JOIN (
  SELECT ROUND(SUM(vote)/COUNT(vote), 2) as vote, questionid
    FROM mdl_studentquiz_vote
    GROUP BY questionid
   ) vo ON vo.questionid = q.id
 LEFT JOIN (
  SELECT ROUND(1 - (COALESCE(correct.num, 0) / total.num), 2) AS difficultylevel,qa.questionid
    FROM mdl_question_attempts qa
     LEFT JOIN (
      SELECT COUNT(*) AS num, questionid
       FROM mdl_question_attempts
       WHERE rightanswer = responsesummary
       GROUP BY questionid
     ) correct ON (correct.questionid = qa.questionid)
     LEFT JOIN (
      SELECT COUNT(*) AS num, questionid
       FROM mdl_question_attempts
       WHERE responsesummary IS NOT NULL
       GROUP BY questionid
     ) total ON (total.questionid = qa.questionid)
    GROUP BY qa.questionid, correct.num, total.num
 ) dl ON dl.questionid = q.id
 LEFT JOIN (
  SELECT COUNT(questionid) as practice, questionid
   FROM mdl_question_attempts mqa
   WHERE responsesummary IS NOT NULL
   GROUP BY questionid
 ) pr ON pr.questionid = q.id
 LEFT JOIN (
  SELECT COUNT(comment) as comment, questionid
   FROM mdl_studentquiz_comment
   GROUP BY questionid
 ) co ON co.questionid = q.id
 WHERE q.parent = 0 AND ((q.category = 22173))
 ORDER BY q.qtype ASC, q.name ASC;
```




good:
```
EXPLAIN SELECT q.hidden, q.category, q.id, q.qtype, q.name,
 q.questiontext, q.questiontextformat, qc.contextid, q.createdby,
 uc.firstnamephonetic AS creatorfirstnamephonetic,
 uc.lastnamephonetic AS creatorlastnamephonetic,
 uc.middlename AS creatormiddlename,
 uc.alternatename AS creatoralternatename,
 uc.firstname AS creatorfirstname,
 uc.lastname AS creatorlastname,
 q.timecreated, ap.approved, vo.vote, dl.difficultylevel, pr.practice, co.comment
FROM mdl_question q 
 JOIN mdl_question_categories qc ON qc.id = q.category
 LEFT JOIN mdl_user uc ON uc.id = q.createdby
 LEFT JOIN
  (SELECT questionid, approved FROM mdl_studentquiz_question) ap ON ap.questionid = q.id
 LEFT JOIN (
  SELECT ROUND(SUM(vote)/COUNT(vote), 2) as vote, questionid
    FROM mdl_studentquiz_vote
    GROUP BY questionid
   ) vo ON vo.questionid = q.id
 LEFT JOIN (
  SELECT ROUND(1 - (COALESCE(correct.num, 0) / total.num), 2) AS difficultylevel,qa.questionid
    FROM mdl_question_attempts qa
     JOIN mdl_question q1 ON qa.questionid = q1.id AND q1.category = 21987
     LEFT JOIN (
      SELECT COUNT(*) AS num, questionid
       FROM mdl_question_attempts
       JOIN mdl_question q4 ON mdl_question_attempts.questionid = q4.id AND q4.category = 21987
      WHERE rightanswer = responsesummary
       GROUP BY questionid
     ) correct ON (correct.questionid = qa.questionid)
     LEFT JOIN (
      SELECT COUNT(*) AS num, questionid
       FROM mdl_question_attempts
       JOIN mdl_question q3 ON mdl_question_attempts.questionid = q3.id AND q3.category = 21987
       WHERE responsesummary IS NOT NULL
       GROUP BY questionid
     ) total ON (total.questionid = qa.questionid)
    GROUP BY qa.questionid, correct.num, total.num
 ) dl ON dl.questionid = q.id
 LEFT JOIN (
  SELECT COUNT(questionid) as practice, questionid
   FROM mdl_question_attempts mqa
   JOIN mdl_question q2 ON mqa.questionid = q2.id AND q2.category = 21987
   WHERE responsesummary IS NOT NULL
   GROUP BY questionid
 ) pr ON pr.questionid = q.id
 LEFT JOIN (
  SELECT COUNT(comment) as comment, questionid
   FROM mdl_studentquiz_comment
   GROUP BY questionid
 ) co ON co.questionid = q.id
 WHERE q.parent = 0 AND ((q.category = 21987))
```

**Comment by eXpl0it3r** [comment] 2017-05-14 23:13
If you want to, you could provide a PR, otherwise I'll look into getting this fixed.

**Comment by nwp90** [comment] 2017-05-15 22:48
I'm not sure of the best way to provide the category ID to the column classes. Not really familiar with this area of Moodle so not sure whether it would be better to add params to the get_extra_joins functions, or to the column constructors, or...

**Comment by nwp90** [comment] 2017-05-23 01:32
Testing fix now.

**Comment by eXpl0it3r** [comment] 2017-05-23 15:04
If you refer to the created branch, it's only a partial fix so far. I'm still investigating how the category can be passed to the query.

If you have found a good fix for it, let us know.

**Comment by nwp90** [comment] 2017-05-24 21:33
I've got a working fix. Will post "soon".

**Comment by nwp90** [comment] 2017-05-25 04:04
See PR#18

**Comment by eXpl0it3r** [comment] 2017-05-30 18:45
This seems to be fixed with e5ba7622475a37828133702c0e2362ba0764daca thanks to @nwp90's work!

Since I don't have a Moodle setup with hundreds (or thousands) of questions, we'd appreciate if some more could potentially test that in their Moodle that has such large number of questions.

**Closed by eXpl0it3r** 2017-05-30 18:45 UTC

**Comment by nwp90** [comment] 2017-05-30 23:57
For anyone testing - I think it's more the number of times students have attempted the questions, rather than the number of questions, which slows it down.

**Comment by reactor0138** [comment] 2017-05-31 00:06
If there is any testing and doubts it's a question of how it's going to work in 3.3 with no orphaned sections and what will happen to a course that already has 2500 questions in it unrelated to the student quizzes. Cause every time someone does a student quiz it creates a new quiz and a category (with loads of writing to describe it). This is not sustainable. We have over 30 student quizzes and 200 students that will be hammering this course for the next 6 months. I am at a point where I think I'll have to put all the student quizzes in a new course just in case something goes wrong and stuffs up the entire revision course we already have. Does it really need to create new category and quiz in section 999 every time a student filters and does a quiz?

**Comment by frankkoch** [comment] 2017-05-31 16:23
The release 2.0.3 of StudentQuiz performs so much better! Thank you very much for your contributions. I tested a StudentQuiz activity with 350 questions being used in 1250 quizzes. The activity opens fast and it took 8 seconds to create a new quiz over all 350 questions.

I'm still not happy with the long list of quizzes in section 999. That looks ugly and I hope to find a better way to store the history of quizzes.

**Comment by reactor0138** [comment] 2017-05-31 20:19
Thanks Frank, I think we are just as concerned with the creation of a new category every time a new quiz is taken too. We'll keep an eye on it here with our super revision course
