### ISSUE TITLE
question category deleted after some time

### ISSUE THREAD

**Issue by rschrenk** [frankkoch/moodle-mod_studentquiz#173] opened 2019-12-03 08:57 UTC
Hello,

we are running Moodle 3.5.7+ (20190830) and mod_studentquiz 2019082900.

We had the very same issue now several times and have not idea what is causing this.

1. Create studentquiz
2. Use studentquiz
3. After several days suddenly the question category and all included questions are gone, simply not there anymore

In those studentquizzes where we created a new category manually, this did not happened again. But in every fresh studentquiz this happens with the question category that was created together with the module.

Kind regards

**Comment by miroi** [comment] 2019-12-03 10:32
Thanks for reporting ! I confirm that I got two times all questions in StudentQuiz lost, now I know that this is due to deleting of the question category.

**Comment by dionysius** [comment] 2019-12-14 02:41
Hi, thanks for the report and sorry for the delay, I was on vacation ;)

First, I very like to know how this can happen. We all of the team can't reproduce it, but it happened as well (assuming it's the same issue)

Your title exactly suggest what I think where the source of the bug lies, but I was unable to look into the database because I can't have access to them because of confidental reasons.

What I think is going on is *somehow* the question category is not *fine* anymore. Some code in studentquiz or moodle (yes, could be a consistency check in the cronjob or so) think that category is not needed anymore and deletes it. Whenever studentquiz is used it *should* create such category if missing. That's why I'm focusing on finding out why the question category gets deleted (or otherwise internally invalidated).

So, theoretically it's impossible to delete questions once at least one question attempt is made on them, since the question lib delete function works exactly like I just described. So everyone using that function this rule applies.  But that doesn't prevent a special case, like *maybe* in the cronjob, if such thing exists.

Do you still have that studentquiz instance? Because I really want to know if the questions are still in the database, but for that you need to know/find at least one question, where you're sure that it belonged to exactly that instance. From there try to find the question category and look if it's missing or what the reason for hiding/invalidating that might be. Thats why we need to look into the database and work up from there.

That's why I have such a hard time to track down that issue (cc @miroi) because, if I do it myself, I need access to that database which is probably a production moodle and thus is very difficult to comply with laws, policy of the affected organisation, privacy issues with the users, etc. to get there. That's also why I'm unable to do that in my former university.

My hands are bound and because I can't reproduce it I need your help. I'd sign an NDA or could go with peer debugging. Just something somehow and asap have a look into it the next time it happens

**Comment by dionysius** [comment] 2019-12-14 02:46
Very likely the same issue as #109

**Comment by rschrenk** [comment] 2019-12-14 13:03
Hi,
I will check the database and give you all information that can be recovered based on one of the studentquizzes.

- Table: studentquiz, id=1, course=2618, coursemodule=67960
- Table: modules, id=50, name=studentquiz
- Table: course_modules, id=67960, course=2618, instance=10, module=50, section = 13555
- Table: course_sections, id=22207, exists.
- Table: context, id=133035, contextlevel=70, instanceid=69490
- Table: question_categories: none for context 133035
So that seems correct.

Unfortunately I  can not check if the questions would still be there, as I moved them out of the question_category BEFORE the category was lost.

For another quiz with instanceid 18414 and contextid 57731 we recreated a hosting category and since we recreated that category (and entered 1 question) it was not deleted again! So it seems this happens only once per studentquiz.

I chose one of the persons that created questions in that studentquiz and checked all categories these questions reside in (categoryids were 19207,27774,28186,28462). Only two existed (19207,28462).

I checked for questions in the other (missing) categories, and they really were there!

So I would assume, if a cronjob removes the category, it would remove (or move) the questions too...

Kind regards

**Comment by rschrenk** [comment] 2019-12-16 10:07
We now realized, that only questions were kept that were connected with tags. All questions without tags were lost.
Perhapts there is really something like a garbage collector interfering.

**Comment by dionysius** [comment] 2019-12-17 12:52
> We now realized, that only questions were kept that were connected with tags. All questions without tags were lost.
> Perhaps there is really something like a garbage collector interfering.

Wouldn't you think these question stayed because it was more likely they had an attempt because they were tagged and the others weren't?

Or you could look for them that way: Are in the table question_attempts some entries from your found list of deleted questions (27774,28186)? I assume no - well, if something is cleaning up it might clean it up correctly...

**Comment by rschrenk** [comment] 2019-12-17 14:34
Unfortunately I can not say definitely what the reason was.

**Comment by dionysius** [comment] 2020-01-05 22:18
Pushed a change related to the default category https://github.com/frankkoch/moodle-mod_studentquiz/commit/bcb2703597a0335d464adb85b091c8c901ee0673, the code might fix internals with a question category, but I don't think it will fix this issue.

**Comment by goggo24** [comment] 2020-01-13 22:28
We have the same problems in our instance => questions have simply disappeared!
In the logfiles it's visible that questions have been created in category x, they haven't been moved or delete. Now if students create question another category id is associated. So it looks like that the question category in student quiz changed on some point. 
![studentquiz](https://user-images.githubusercontent.com/16721900/72296984-3063eb80-365b-11ea-8848-3be77a371f96.png)
We tried to reproduce it, but we have not been successful so far. Which information would help you? We use Moodle 3.7.4 (Build: 20200113) with studentquiz (2019040100).

**Comment by dionysius** [comment] 2020-01-14 11:41
Let's try to act quickly. I also have a hard time to recreate it. Can you look in the database, if:

1. the missing questions can be found in the database in the table `mdl_questions` (since you know all the affected `question_id`'s)
2. If yes, for all affected ids? (If you have many questions, try to make a good sample size).
3. The `mdl_questions` table has also a column `category`. Write that down and try to find the related category in table `mdl_question_category`. Can this category be found?
4. If yes, please get me the full row for a) this "lost" category and b) the currently assigned category of this studenquiz. I really want to make a diff from these two lines in hope I find out what's wrong...

p.s. If 2) is yes, you can restore this questions by editing the column `category` to the currently active category id of the effected `question_id`s

**Comment by dionysius** [comment] 2020-01-14 11:50
It is also good to know that now we know it happens on Moodle35 and Moodle37.

**Comment by goggo24** [comment] 2020-01-14 12:04
@1 & @2: the questions till exists, ...
@3: but the related category id does'nt exist anymore
As a workaround i just have overwritten the question category belonging to the question, so that our teachers see them in the question bank. I didn't wanted to use the category belonging to the student quiz, because I'm not sure if the questions won't disappear again, so I created a new  question category in the course. I will try to send you more information the next days.

**Comment by dionysius** [comment] 2020-01-14 13:16
Thank you very much for looking that up! Now we know definitely that (only) the category disappears, for whatever reason is still part of resolving this issue

**Comment by dionysius** [comment] 2020-03-02 15:22
Has anyone experienced this issue again since https://github.com/frankkoch/moodle-mod_studentquiz/commit/bcb2703597a0335d464adb85b091c8c901ee0673 (which is included in StudentQuiz since v4.0.5) - It basically ensures a default question category in our context exists.

I have a hard time fighting this issue by not being able to reproduce it and not finding anything wrong in the code while reviewing.

If this happens, I need the (database) situation exactly before the issue happened, so basically hopefully a(n) (anonymized) course backup can maybe help.

**Comment by rschrenk** [comment] 2020-03-25 05:58
Unfortunately, yes.

We are using plugin version v4.1.1 (build 2020013000) on Moodle 3.5.11 and suffered from this bug several times in the last week. 

In such a case the following steps help me to recover the questions:

1. I search in the questions table for questions by the createdby-attribute for the userids of students in the course. Students normally do not have many questions, so I can identify the old category id.
2. In the course module  I go to the question bank and grasp the new categoryid
3. A simple UPDATE-query recovers all questions

We experienced that the loss of the category only happens once.

**Comment by miroi** [comment] 2020-03-27 21:31
Unfortunately, yes. 

In Moodle 3.7, StudentQuiz v4.1.2. The question category of the StudentQuiz instance disappeared with more than 600 questions..

From course logs I can identify the ID of the category, because people (fortunately) were working within this category (creating, updating questions) few days ago. The StudentQuiz category had few subcategories, which I used for exporting subsets of creating questions.

It is strange that it is only the StudentQuiz category which disappears (not for the first time), but  all question categories of the course (so called non-StudentQuiz categories) remain intact. Maybe Tim ( @timhunt  ) can comment this ?

**Comment by timhunt** [comment] 2020-03-28 19:13
I can't think of anything in standard Moodle that woud delete a question-category at a random time. I think a category is only deleted if: A user deletes it in the UI, or if a Course or activity witha question bank is deleted. Then Moodle deletes that question bank.

And, I have skimmed thorugh throug the StudentQuiz code searching for things like category and delete, and cannot see anything that looks like the cause.

I did see some other worrying things. For example: https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/lib.php#L215
* First of all, you don't need to do this. Moodle automatically deletes all the questions and categories when an activitiy is deleted.
* Second, just deleting the rows from the question_categories table is wrong. That leaves all the question data just stuck in the database.

And, I am pretty sure there is a similar bug to the second problem here in function mod_studentquiz_migrate_old_quiz_usage: https://github.com/frankkoch/moodle-mod_studentquiz/blob/master/locallib.php#L1177. I'm pretty sure you can't just delete course_sections rows.

------

As @dionysius says, we can't hope to fix this until we can reproduce it. The "Very likely the same issue #109" suggests that the trigger might be restoring the backup of a different studentquiz. I will note that the restore is what calls that scarey mod_studentquiz_migrate_old_quiz_usage function.

------

I also note the comments above that some people found that the questions were not deleted, just the row from the question_categories table, so it is possible to manually repair this.

It is a mystery. Small prize to anyone who can work out how to reproduce this. (The prize will probably be getting this bug fixed ;-))

**Comment by miroi** [comment] 2020-03-29 09:03
Well, one unfortunate feature is that upon restoring the lost category all attached files are lost. In my case these are png-pictures, inserted into question pages.

**Comment by tiocca** [comment] 2020-04-14 12:09
In my case, the category and the Questions are completely lost (gone from mdl_questions).

**Comment by rschrenk** [comment] 2020-04-21 10:32
It happens again and again and again.
Unfortunately I hat to remove the capability, that users can add new studentquiz instances. What a pitty, it would be a great plugin.....

**Comment by dionysius** [comment] 2020-04-23 20:38
I should've found the cause! (**Since I can't reproduce it, I can't guarantee that to you!**)

The hint of @timhunt got me thinking about the restore code. While none of his suggested parts seem to be _really_ (carefully said) related, I found this: https://github.com/frankkoch/moodle-mod_studentquiz/commit/bd0bd8368d1a57e9b843b236a9186ff2c33b8914.

This function was introduced in StudentQuiz 3.0.3 https://github.com/frankkoch/moodle-mod_studentquiz/commit/05e17080f835b097d76e13215790c28bb8209a5a, since Moodle introduced the so called "top" category in Moodle 3.5 (I still don't know today what it actually does, you can't assign anything to it, it's just there). At that time it buzzed me to introduce such a drastic change directly into the LTS - but I thought they would sure about that - today we're happy about this.

Before that, the category was somehow created with a parent id (the StudentQuiz id if i remember correctly) while it now must match the "top" category id (otherwise you don't have the parent-child relation of course). Moodle didn't fix that during import for us (If I remember correctly, they migrated it only correctly when it was unset), so we had to fix it manually for both variants.

But dangerous about this function was, that it went always over all StudentQuizzes in the whole Moodle to try to fix this (well, it actually didn't try, _it just did always_) **if a restore had a StudentQuiz in it**. That can happen pretty often nowadays! This is why I'm pretty sure this issue boils down to that. All other import/migration functions have explicitly the course or the StudentQuiz id to limit the "spread" of affected instances. While quickly glancing over that function it doesn't look wrong, but it was also not needed the longer time went by and schools and universities upgraded StudentQuiz and Moodle.

Since Moodle officially only supports 3.5 and newer, which we match, we luckily now can just get rid of that function completely. There is a catch tho, if someone has a backup of a course with StudentQuiz in it before Moodle 3.5 and before StudentQuiz 3.0.3, they'll have a wrong category parent if the'd try to import that. On the Moodle plugin page we officially support the updating path from 3.0.0 and onward, so 3.0.3 is still in it. (But I'm happier to solve this issue than worrying about that).

But maybe it's time for a new supported upgrade path breakpoint.

> I'm pretty sure you can't just delete course_sections rows
Yes, you might be right, but we had to. I think you don't know how StudentQuiz was in the 2.x.x era, you'd be surprised and hold your hand on your head. Big story for people who know the Moodle code. But in the other hand, this function is also to be considered to be removed for the same reason to be not needed anymore related to the wished support range.

I'll go into the other points as well before the next release

**Comment by lordsamax** [comment] 2020-04-28 16:37
Hello! Any solution to this issue? I just got my question deleted

**Comment by dionysius** [comment] 2020-04-30 09:21
Yes, the potential fix is already merged and will be included in the next release. I try to fix some minor things today so I can release the next version today

**Comment by dionysius** [comment] 2020-05-01 00:12
Next release is out! As already mentioned, I will need your feedback to conclude the state of this issue

**Comment by rschrenk** [comment] 2020-05-02 00:03
Great, I installed that updated. We will see if it works!

**Comment by ewallah** [comment] 2020-05-10 08:08
The latest version generates a Risky test warning in phpunit and extra output:

```
vendor/bin/phpunit --colors "core_calendar_container_testcase" calendar/tests/container_test.php
Moodle 3.8.3 (Build: 20200511), 5afef2670e77c66c3671d7ef07e6514a77ac7835
Php: 7.3.17.1.18.04.1.1, pgsql: 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1), OS: Linux 4.15.0-99-generic x86_64
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

................R<table class="generaltable">
<thead>
<tr>
<th class="header c0" style="" scope="col">Category</th>
<th class="header c1 lastcol" style="" scope="col">Action</th>
</tr>
</thead>
<tbody><tr class="">
<td class="cell c0" style="">top</td>
<td class="cell c1 lastcol" style="">This category has been deleted because, after deleting the course, its questions weren't used any more.</td>
</tr>
<tr class="lastrow">
<td class="cell c0" style="">Default for studentquiz 0</td>
<td class="cell c1 lastcol" style="">This category has been deleted because, after deleting the course, its questions weren't used any more.</td>
</tr>
</tbody>
</table>
.                                                18 / 18 (100%)

Time: 8.17 seconds, Memory: 91.00 MB

There was 1 risky test:

1) core_calendar_container_testcase::test_delete_module_delete_events
This test printed output: <table class="generaltable">
<thead>
<tr>
<th class="header c0" style="" scope="col">Category</th>
<th class="header c1 lastcol" style="" scope="col">Action</th>
</tr>
</thead>
<tbody><tr class="">
<td class="cell c0" style="">top</td>
<td class="cell c1 lastcol" style="">This category has been deleted because, after deleting the course, its questions weren't used any more.</td>
</tr>
<tr class="lastrow">
<td class="cell c0" style="">Default for studentquiz 0</td>
<td class="cell c1 lastcol" style="">This category has been deleted because, after deleting the course, its questions weren't used any more.</td>
</tr>
</tbody>
</table>

To re-run:
 vendor/bin/phpunit --colors "core_calendar_container_testcase" calendar/tests/container_test.php

OK, but incomplete, skipped, or risky tests!
Tests: 18, Assertions: 85, Risky: 1.
```

**Comment by dionysius** [comment] 2020-05-17 13:04
I now has been over 2 weeks since the last version is out. Feel free to comment here

**Closed by dionysius** 2020-05-17 13:04 UTC
Labels: bug, help wanted, need more info, ready for release

**Comment by qchan-mindfield** [comment] 2024-04-05 15:47
It's 2024 and somehow this issue is still occurring. It happened twice where a question bank category just disappeared. One of the replicable instances was a teacher was trying to create a subcategory and did it incorrectly. They renamed the category when editing a parent category and it made the category disappear. The questions associated are now just floating in Moodle space without a category.
