### ISSUE TITLE
Unable to change question state on quiz overview in StudentQuiz

### ISSUE THREAD

**Issue by atbinix** [frankkoch/moodle-mod_studentquiz#278] opened 2020-10-14 02:02 UTC
Hi, 
An issue with changing question state, here is the replication steps:

1- Add a "studentQuiz" activity in a course
2- Enter any title and description and save
3- Click “Create new question” and create any question
4b- On quiz overview, click the box to change the question state [screenshot] 
![Step4b](https://user-images.githubusercontent.com/19506513/95934146-b34aea00-0e17-11eb-994a-d4760a67f07b.png)
4a- Or click the “Change state” tab/section with questions ticked [screenshots]
![Step4a](https://user-images.githubusercontent.com/19506513/95934142-b1812680-0e17-11eb-9cde-27dd21c39dac.png) 
5- Attempt to change the state in both situations for any of the available states and click on "Change state" [screenshots]
![Step5a](https://user-images.githubusercontent.com/19506513/95934629-dc1faf00-0e18-11eb-9872-ff6fa4229228.png)
![Step5b](https://user-images.githubusercontent.com/19506513/95934632-dd50dc00-0e18-11eb-98b9-319b1091fc10.png)
**Observed**: Unable to change question state by clicking on the “Change state” button as it's not functioning (greyed out). 
**Expected**: Able to change question state from clicking the change question state box on student quiz overview. 
_Note that changing question type is allowed from the question preview or when starting the quiz. Just that this particular way of changing it is greyed out. Latest version, tested on Chrome and Firefox._

**Comment by dionysius** [comment] 2020-10-14 02:45
This should've been adresses by #262, duplicate of #218, and is included in the next release.

**Comment by atbinix** [comment] 2020-10-14 02:55
Sure, thank you.

**Comment by dionysius** [comment] 2020-11-06 16:01
#262 is not sufficient. I've marked this issue as the main issue now, since it provides a more detailed report. #218 was the previous one

**Closed** 2021-02-22 10:25 UTC
Labels: bug, help wanted, minor
