### ISSUE TITLE
mod_studentquiz: Student Quiz activity does not save when using Calculated Simple Question

### ISSUE THREAD

**Issue by kiratskitizing** [frankkoch/moodle-mod_studentquiz#269] opened 2020-10-02 02:27 UTC
Moodle
$release  = '4.0dev (Build: 20200929)'

Student quiz
$plugin->version      = 2020081100;
$plugin->release      = 'v4.3.3';

When using student quiz activity, a user/student adding a Calculated Simple Question is not able to save the activity.

Steps to Replicate
1. Create a course and enrol at least 1 student.
2. Click on “Turn editing on”
3. Click “Add an activity or resource”
4. Select “StudentQuiz”
5. Enter any title and description and save
6. Sign in as student
7. Go to the student quiz activity
8. Click “create new question” and select “Calculated Simple”
- Enter whatever title
- Enter any question text such as {b}*{h}
- Put any answer in answer formula such as {b}*{h} and set grade to 100%
- Leave other variables as preset
- Click “find wild cards present in current formula”
- Click “generate”
9. Click “save changes”

OBSERVED BEHAVIOR
Page refreshes without proceeding to question bank and acts like “save changes and continue editing”. 

EXPECTED BEHAVIOR
Page saves and question added to quiz

**Comment by dionysius** [comment] 2020-10-06 12:16
I can confirm this is a bug. The student can't add the question, but the admin can (obviously) and an enrolled teacher can as well.

**Comment by dionysius** [comment] 2020-10-06 12:23
Right now I can't exactly say where the source of this issue is. But I assume a permission issue.

This is the current permission matrix for that activity context:
![image](https://user-images.githubusercontent.com/1341084/95200921-75c6db00-07df-11eb-8291-7ac0b4499d4d.png)

**Comment by dionysius** [comment] 2020-10-06 13:21
The admin can't save the question as well when the `Generate` button was not pressed, that's why I looked deeper at what happens there.

The permission required to save for the student seems to be `moodle/question:movemine` (by bruteforce testing all missing question capabilities one by one). Looking at the code of calculated simple question type (which is around 11 years old) it is very based on the calculated question type. I can vaguely see that it creates a temporary question (or part of the question in form of `itemset`) before actively beeing "placed". These `itemset`s are created when using the `Generate` button. I assume under the hood that this `move`s the question or part of the question (`itemset`) onto the right place.

Now, I remember to beeing very careful with the `move` capability when I was looking into the permissions. As this, as far I remember, allows to move *any question* to a category the context where the student has permission on. There is no check if the student has permission to *take away* the question from the old place - he might not have permission there at all. Needs further checking.

If `moodle/question:movemine` is safe to use for the student, the fix is simple. But this question needs to be addressed.

That's all I have for today.

**Comment by dionysius** [comment] 2020-10-06 13:44
I mean, it doesn't sound too harsh and maybe that's the price we have to pay. I just meant, we set context specific permission overrides and this would allow the student to do something from/to outside of this exact context. Maybe @timhunt has an opinion on that.

**Comment by timhunt** [comment] 2020-10-06 13:49
Move capability should not be required to create a question. This is a bug in core calcualted question type. Please report it at https://tracker.moodle.org/.

I don't think studentquiz activity should attempt to work-aroudn this core bug.

**Comment by dionysius** [comment] 2020-10-06 14:49
Reported: https://tracker.moodle.org/projects/MDL/issues/MDL-69872

**Comment by dionysius** [comment] 2020-10-06 16:20
I've changed this issue to wontfix, as this is not a bug of StudentQuiz right now, but I wouldn't close that for now. I'd keep an eye open on what happens on the moodle tracker. You can make a workaround hack and support that question type by adding the capability `moodle/question:movemine` for students on course level or even system, **but be warned: I can't say what unexpected permissions side effects this has!**. Please refer to the moodle documentation: https://docs.moodle.org/39/en/Capabilities/moodle/question:movemine

**Comment by kiratskitizing** [comment] 2020-10-07 01:45
Thank you everyone.

**Comment by dionysius** [comment] 2020-11-06 16:15
There has not been a response within a month on the moodle tracker. I'm closing this, feel free to reopen it once there's a solution at moodle. In the meantime the workaround provided should be sufficient.

**Closed by dionysius** 2020-11-06 16:15 UTC
Labels: need more info, wontfix
