### ISSUE TITLE
Student quiz does not work well with strange Roles setups

### ISSUE THREAD

**Issue by timhunt** [frankkoch/moodle-mod_studentquiz#64] opened 2018-10-24 11:20 UTC
At the Open University, we have lots of custom roles defined, many of which do not follow any of the Moodle 'archetypes'. Because of that, the logic in mod_studentquiz_ensure_question_capabilities does not work for us. I plan to think about that in details, and suggest a fix, but I have not done that yet.

In addition, studentquiz does not implement the studentquiz_get_extra_capabilities function to say that the question bank capabilties are relevant to studentquiz, therefore, it is not currently possible to fix the permissions manually. This bit is easert to sort out, and I have a commit for that already.

**Comment by frankkoch** [comment] 2018-10-24 13:11
Thank you Tim for your contribution. We also have some commits. I will wait for your next commit and then its getting time for SQv3.1.2.

**Comment by timhunt** [comment] 2018-10-25 15:43
Here is the second commit, which changes the studentquiz_get_extra_capabilities logic.

The implementation I have gone for is, for any role with permission to submit questions in the StudentQuiz, ensure that role has the necessary question permissions. However, it only bothers to add an override if that role does not already have the permissions. I hope that works in all cases.

While looking into this I found all the TODOs in load_questionbank in viewlib.php. I would love to have a go at cleaning that up, but I don't have time today. (Also, if you are about to release a new version, now is not a good time for radical surgury like that.)

**Comment by frankkoch** [comment] 2018-10-26 15:06
Thank you again for this contribution. We will publish it in the next release, most likely next week.

If you have time for the TODOs, you're most welcome :-)

**Comment by frankkoch** [comment] 2018-11-01 21:00
Hi Tim, there is a problem with commit 147d965. It causes the error "you must select a question type" when a student adds a question. However, teacher can add questions.

**Comment by frankkoch** [comment] 2018-11-16 15:52
I just tried to reproduce the scenario and this time I figured out that the error occurs even before I cherry-picked 147d965. So it looks like this error is not in your code but in the latest commits of our develop4-branch. It's tricky, because the error happens just "sometimes". So in my first tests, it appeared just after I installed picked 147d965. This time, it came up before.

Sorry Tim, it's obviously not your code which causes the error. We have to reconsider the last commits in the develop4-branch.

**Comment by timhunt** [comment] 2018-11-16 15:54
No worries. I think the improvements to the Behat test are a good thing anyway :-)

There is even a chance that teh cahnges in my second commit might solve the problem? (I'm not sure what the problem is though.)

**Comment by frankkoch** [comment] 2018-11-16 16:01
To describe the problem: when a student does "Create new question" he gets:
![capture](https://user-images.githubusercontent.com/12372991/48632269-c2715500-e9c0-11e8-8b7c-13ad6416ab02.JPG)

However, when you try a 2nd, 3rd, 4th, .. time, eventually the "Choose a question type to add" window pops up. This is without any of your commits. It sometimes even happens with the teacher role.

**Comment by frankkoch** [comment] 2018-11-16 16:04
Ah, just to add, it happens with our latest develop4-branch.

**Comment by timhunt** [comment] 2018-11-16 17:45
If that is happening then what it means is that the JavaScript that handles that 'Create new question' button has not initialised before you click the button. (So it does a normal form submit to that 'Choose a question type to add' page.) So, open your browser console while the page loads, to see if there are any error messages. 

This is standard Moodle javacript (question/yui/src/chooser/js/chooser.js) and I have not heard of it failing before, but if need be try putting a break point in initializer there.

I just tried with your develop4 branch, but I could not make the problem happen on my computer.

On the 'You must select a question type' page, it should show the list of question types, so you can select on there and then click continue. Does it do that? (I suppose the other issue might be that the list of allowed question types is empty. I am not sure what would happen in that case.)

Not sure if any of that is helpful.

**Comment by frankkoch** [comment] 2018-11-29 17:22
released with 3.2.0

**Closed by frankkoch** 2018-11-29 17:22 UTC
