### ISSUE TITLE
"invalid course module ID " when filtering questions

### ISSUE THREAD

**Issue by miroi** [frankkoch/moodle-mod_studentquiz#51] opened 2018-05-23 08:12 UTC
Hello,

with the newest 3.0.3 StudentQuiz when I want to filter questions via family name and first name I get this error
~~~
Invalid course module ID

More information about this error
~~~

Any help, please ?

**Comment by dionysius** [comment] 2018-05-23 13:01
Sounds like a duplicate of https://github.com/frankkoch/moodle-mod_studentquiz/issues/39, issue is known but not actively tracked here on github

**Closed** 2018-10-04 08:43 UTC
